<?php

// autoload_classmap.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'StupidHttp_Mock_WebServer' => $baseDir . '/src/StupidHttp/Mock/WebServer.php',
    'StupidHttp_Mock_NetworkHandler' => $baseDir . '/src/StupidHttp/Mock/NetworkHandler.php',
);
